name = "repllabs"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat_v2"]
workers_dev = true
main = "./build/server/index.js"
# https://github.com/remix-run/react-router-templates/issues/8
assets = { directory = "./build/client/" }

routes = [
  { pattern = "repllabs.com", custom_domain = true }
]

[vars]
VALUE_FROM_CLOUDFLARE = "Hello from Cloudflare"
